# Generated by Django 3.0.5 on 2020-05-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppartmentModel',
            fields=[
                ('appartmentno', models.IntegerField(primary_key=True, serialize=False)),
                ('flatno', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('noofflats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CreatePlotModel',
            fields=[
                ('plotno', models.IntegerField(primary_key=True, serialize=False)),
                ('roadno', models.IntegerField()),
                ('surveyno', models.IntegerField()),
                ('costpersqyard', models.DecimalField(decimal_places=2, max_digits=10)),
                ('otherexpences', models.CharField(max_length=30)),
                ('boundaries', models.CharField(max_length=200)),
                ('facing', models.CharField(choices=[('east', 'EAST'), ('west', 'WEST')], max_length=30)),
                ('status', models.CharField(choices=[('vacant', 'VACANT'), ('reserve', 'RESERVE'), ('sold', 'SOLD')], max_length=15)),
                ('totalcost', models.DecimalField(decimal_places=2, default=True, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('empid', models.IntegerField()),
                ('mail', models.EmailField(max_length=100)),
                ('location', models.CharField(max_length=40)),
                ('doj', models.DateField()),
                ('role', models.CharField(choices=[('general manager', 'GENERAL MANAGER'), ('acounts manager', 'ACOUNTS MANAGER'), ('sales manager', 'SALES MANAGER'), ('sales representative', 'SALES REPRESENTATIVE'), ('accountant', 'ACCOUNTANT'), ('accounts assistance', 'ACCOUNTS ASSISTANCE'), ('clerk', 'CLERK'), ('receptionist', 'RECEPTIONIST'), ('security', 'SECURITY')], max_length=30)),
                ('qualification', models.CharField(max_length=30)),
                ('remarks', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('admin', 'ADMIN'), ('user', 'USER')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SalesModel',
            fields=[
                ('plotno', models.IntegerField(primary_key=True, serialize=False)),
                ('salevalue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dateofsale', models.CharField(max_length=40)),
                ('advance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('installment', models.CharField(max_length=10)),
                ('soldto', models.CharField(default=True, max_length=30)),
                ('check', models.CharField(default=True, max_length=30)),
                ('payeename', models.CharField(default=True, max_length=30)),
            ],
        ),
    ]
