# Generated by Django 3.0.5 on 2020-06-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('empid', models.IntegerField()),
                ('mail', models.EmailField(max_length=100)),
                ('location', models.CharField(max_length=40)),
                ('doj', models.CharField(max_length=40)),
                ('role', models.CharField(choices=[('general manager', 'GENERAL MANAGER'), ('acounts manager', 'ACOUNTS MANAGER'), ('sales manager', 'SALES MANAGER'), ('sales representative', 'SALES REPRESENTATIVE'), ('accountant', 'ACCOUNTANT'), ('accounts assistance', 'ACCOUNTS ASSISTANCE'), ('clerk', 'CLERK'), ('receptionist', 'RECEPTIONIST'), ('security', 'SECURITY')], max_length=30)),
                ('qualification', models.CharField(max_length=30)),
                ('remarks', models.CharField(max_length=30)),
            ],
        ),
    ]
